### ISSUE TITLE
Social media links on /contact refresh page

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#435] opened 2016-06-17 14:53 UTC
The social media links on the right side of /contact refresh the page rather than link to the social media account.

https://www.westcarrollton.org/contact/ 
https://warr-acres-ok.proudcity.com/contact/

**Comment by aschmoe** [comment] 2016-06-28 23:33
Duplicate of #389, closing

**Closed** 2016-06-28 23:33 UTC
Labels: ZenDesk
