### ISSUE TITLE
SR: content disappears on the edit screen

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1477] opened 2018-12-16 21:56 UTC
https://www.cityofsanrafael.org/recurring-monthly-parking-payments/
<img width="1217" alt="screenshot 2018-12-16 16 55 05" src="https://user-images.githubusercontent.com/6032426/50059340-9bd74300-0153-11e9-8d4b-5c6a8565bcc4.png">
<img width="1154" alt="screenshot 2018-12-16 16 56 47" src="https://user-images.githubusercontent.com/6032426/50059341-9bd74300-0153-11e9-9983-72345fbeb3e3.png">

I'm the editor doesn't have a pagebuilder option which I'm assuming it had before because there is an embedded webform. @jlyon could this have been hidden with the parking payment permission stuff or perhaps something with the WP5 upgrade?

**Comment by jlyon** [comment] 2019-01-07 05:52
dupe of #1479

**Closed** 2019-01-11 07:38 UTC
Labels: ZenDesk, duplicate, hotfix, ready
