### ISSUE TITLE
SR: customize order of department list

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#572] opened 2016-09-29 17:20 UTC
Zendesk:
Is there a way we can list the departments based on our analytics (which ones are more popular), rather than in alphabetical order?

I don't think they're asking about it being automated so it would just be the ability to adjust the order of the content list: https://san-rafael-ca.proudcity.com/departments/

**Comment by jlyon** [comment] 2016-09-30 18:24
Dupe of #521

**Closed** 2016-09-30 18:24 UTC
Labels: duplicate, enhancement, ZenDesk
