### ISSUE TITLE
Event location issue

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#2112] opened 2022-09-28 13:11 UTC
**Source**
Beta
https://beta.proudcity.com/event/testing-location-on-event/

**Describe the bug**
Event location dropdown when adding new event does not yield any results even though there are lots of locations under dashboard > events > locations. 

If you enter a new location into the fields, once the event is published the event saves as "event does not have physical location". 

**To Reproduce**
1. Add new event
2. Select location dropdown (no results)
3. Instead enter new location
4. Publish
5. View event
6. "event has no physical location"

**Expected behavior**
Location option should be published

**Screenshots**
![Screen Shot 2022-09-28 at 9 05 51 AM](https://user-images.githubusercontent.com/6032426/192786973-b0fe01c5-0a68-46f2-a375-e8451cb10a66.png)
![Screen Shot 2022-09-28 at 9 09 22 AM](https://user-images.githubusercontent.com/6032426/192786976-44ae5d27-bb65-4ddd-862a-5494702b80ea.png)

**Comment by curtismchale** [comment] 2022-10-11 17:51
@kevindherman I found the issue and it's not with the Events Manager Plugin. The issue is that you need to create a Name for the location you're adding to the event. See the arrow for the event created here: https://beta.proudcity.com/wp-admin/post.php?post=31783&action=edit

![CleanShot 2022-10-11 at 10 41 52@2x](https://user-images.githubusercontent.com/74561/195162380-e3d3621c-b8dc-4b15-b5e9-b715fa67a5c5.png)

So the UI isn't clear and doesn't stop the user from creating a location without a name which won't be saved. It is working as intended by the developer though.

I didn't find a way to officially submit an issue to the developer so I created a [WordPress.org support thread](https://wordpress.org/support/topic/little-user-feedback-is-provided-if-you-dont-name-a-location/#new-topic-0) with my suggestion for better user interaction.

It might be possible for us to add some JavaScript to accomplish this. If the user clicked the publish button with a custom location provided, but no name we could tell them that there is a required field.

**Comment by kevindherman** [comment] 2022-10-13 13:18
@curtismchale that makes sense. It is unclear, especially when Google populates the map information with something that's different from what the user wants. This can be weird if an address has multiple purposes like City Hall and Council Chambers or the Police Department.

**Comment by curtismchale** [comment] 2022-10-13 20:41
@kevindherman so are we resolving this or do we do something about it and make it an issue?

**Comment by kevindherman** [comment] 2022-10-13 21:02
@curtismchale I think resolved.

**Closed** 2022-10-13 22:30 UTC
Labels: bug
