### ISSUE TITLE
Image widget seems to be buggy

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#2591] opened 2024-08-22 23:24 UTC
## Source

LF

## Describe the bug

The image widget seems to randomly not display the title/description text more often than not. It will show correctly at times.

## To reproduce
1. Go to https://help.proudcity.com/books/
2. See error (screenshot below)

## Screenshots

![Screenshot 2024-08-22 at 16-22-38 Books - ProudCity Help Center](https://github.com/user-attachments/assets/defcbab8-6844-4994-9429-3980c3dbb90d)

## QA

Notes:

* 

Links:

*

**Comment by curtismchale** [comment] 2024-09-03 18:36
@lukefretwell I've spent 30 minutes trying to make this happen reliably in a few browsers. I've seen it once and what it looked like was that the JS that equalizes the heights of the cards didn't load as expected thus they defaulted to a smaller size.

Unless you can come up with a way to reproduce this every time this is closing because I'll never chase down the issue.

**Closed by curtismchale** 2024-09-03 18:36 UTC
Labels: bug
