### ISSUE TITLE
'Leave page' prompt when leaving the page

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#1933] opened 2021-12-15 00:15 UTC
**Source**

@lukefretwell 

**Describe the bug**

When leaving a page, even after saving, I sometimes see a 'This page is asking you to confirm that you want to leave ...' alert message. 

**To Reproduce**

1. Go to post or page and edit.
2. Select 'Save.'
3. See message.

**Expected behavior**

After saving and leaving the page, would expect to not receive the message.

**Screenshots**

<img width="444" alt="Screen Shot 2021-12-13 at 2 15 05 PM" src="https://user-images.githubusercontent.com/1569463/146096545-3dad6ca9-031e-42b4-945f-4aa76442b30e.png">

**Desktop (please complete the following information):**

 - OS:  iOS
 - Browser: Firefox

**Comment by kevindherman** [comment] 2021-12-15 13:53
I've been able to replicate this taking certain steps because it's not an all the time thing in my experience. If you hit save and then view page, you don’t get the prompt. However, if you save and wait or navigate to another tab and then return to the original edit page to then select view page, you then get the prompt. It seems like in waiting a certain amount of time or reselecting the tab, the browser/edit page thinks that there is unsaved work. 

@lukefretwell is that your experience? 

@jlyon @aschmoe  what about you guys?

**Comment by jlyon** [comment] 2021-12-16 20:43
Here's the ticket with more details: https://github.com/proudcity/wp-proudcity/issues/1822

**Comment by curtismchale** [comment] 2022-02-08 21:06
For our sites it seems to be an issue with the interaction of the ProudCity theme and the SiteOrigin Page builder. I can reproduce it every time with both of them active from a page that is using SiteOrigin. It does not happen on other pages/custom post types that are not using SiteOrigin.

If I use the default theme the issue goes away.

If I deactivate SiteOrigin the issue goes away as well.

I'll need to look into what the theme may be doing with saving that affects this.

While debugging it I found another issue around saving content with the `[proud_accessibility_shortcode]` being used and pushed a fix to clean that up here: https://github.com/proudcity/wp-proud-core/commit/3e264591e9becac86f58ab55f1b91bc1c8ba1ecc

**Comment by curtismchale** [comment] 2022-02-08 21:49
Fixed when this PR is merged: https://github.com/proudcity/wp-proud-theme/pull/11

**Comment by aschmoe** [comment] 2022-02-11 07:04
@kevindherman @curtismchale 

This is deployed on beta now

**Comment by aschmoe** [comment] 2022-02-11 07:18
@kevindherman looks to me like the result of this is the "Text" tab is default + visible (new?).  Not sure if a deal breaker 

https://beta.proudcity.com/wp-admin/post-new.php?post_type=page

<img width="1777" alt="Screen Shot 2022-02-10 at 11 16 44 PM" src="https://user-images.githubusercontent.com/1634686/153551367-c6d1d1d8-58b9-4f3e-a7c3-4da75e9bfc5a.png">

**Comment by kevindherman** [comment] 2022-02-11 13:02
@aschmoe thanks for flagging and I think this could be a challenge for our customers. 

@lukefretwell what do you think? 

@curtismchale do you think there is a way to have the visual editor as the default without having the prompt even after saving or is that the tradeoff?

**Comment by curtismchale** [comment] 2022-02-11 18:16
@lukefretwell @kevindherman I did just confirm that a new user sees the Visual Editor by default with their new account. IF they select the text editor then it will show them the text editor next time they view any editor. This has been default for the Classic Editor since it was just the regular old editor.

So the only reason someone will see text first is if they choose to see it as far as I can tell.

**Comment by kevindherman** [comment] 2022-02-11 18:27
@curtismchale thanks for confirming. Let's moving forward with the fix.

**Closed** 2022-02-17 05:08 UTC
Labels: bug
