### ISSUE TITLE
Platform wide: event locations google api issues

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1643] opened 2019-12-20 16:01 UTC
I've gotten a couple of tickets about people trying to create events and getting this error:

The error message says: Your event details are incorrect and cannot be published, please correct these errors first:

Something went wrong saving your event to the index table. Please inform a site administrator about this.

I am able to login to their site and publish for them for some reason, however, I am noticing that the location information is showing "not found" when it should. Here's an example on SR Employees site:

https://employees.cityofsanrafael.org/wp-admin/post.php?post=18177&action=edit
![Screenshot 2019-12-20 11 00 38](https://user-images.githubusercontent.com/6032426/71267380-65a94200-2318-11ea-8a6b-3bb72d053be1.png)

And here's the location detail:
https://employees.cityofsanrafael.org/wp-admin/post.php?post=16081&action=edit
![Screenshot 2019-12-20 11 00 08](https://user-images.githubusercontent.com/6032426/71267401-72c63100-2318-11ea-8731-230c7cbbab98.png)

That location is one that's been there for a while and is City Hall which isn't a weird address. I have a feeling this is what's causing the error across the platform.
@jlyon @aschmoe

**Comment by jlyon** [comment] 2019-12-21 22:53
@kevindherman I was able to create a few events on SR employees and never got that error: https://employees.cityofsanrafael.org/wp-admin/edit.php?post_status=trash&post_type=event.  Two of the events had the City Hall location selected, with the error "Location not found" below the address inputs, so maybe it's not that? Have you been able to replicate the issue yourself anywhere?  

I also tried creating an event as a normal Editor user on Colma after I saw the issue in Zendesk from them (title `asdfasdf` on https://www.colma.ca.gov/wp-admin/edit.php?post_status=trash&post_type=event), and wasn't able to replicate the issue there either.

For people that are reporting the issue:
1. Could I get an example username (email address)
2. Does the error persist, or does it just happen once and then fix itself?
3. What other sites have reported the issue?

**Comment by jlyon** [comment] 2019-12-23 01:35
@kevindherman i was able to find the error in the logs:
```
 WordPress database error Unknown column 'event_parent' in 'field list' for query INSERT INTO `wp_em_events`
```

It looks like the events-manager plugin needs some database updates, and those updates occur when the info@ user visits the website, which is why we haven't been able to reproduce.  This means that everyone that has written in and you have logged in to their site (Oakwood, SR Employees, Kettering) is now fixed. I'll look at a fix for the platform later tonight/tomorrow.

Notes to self:
`em_upgrade_current_installation();` in `/em-install.php`
` select*from wp_em_events limit 1;`

**Comment by kevindherman** [comment] 2019-12-23 13:17
@jlyon thanks for finding this!

Colma also mentioned issues so hopefully it's fixed for them now too.

**Comment by jlyon** [comment] 2019-12-23 18:59
@kevindherman verified that Colma looks good. I went through all the prod and test sites and _should_ have fixed this issue on all sites. Lmk if you get any more reports.

**Comment by kevindherman** [comment] 2019-12-23 19:03
@jlyon will do. thank you.

**Closed** 2020-01-29 04:15 UTC
Labels: ZenDesk
