### ISSUE TITLE
Expired jobs still published

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#2214] opened 2023-03-02 23:41 UTC
## Source
Montclair

[* [LINK TO TICKET]](https://proudcity.zendesk.com/agent/filters/73365647)

## Describe the bug
Expired jobs still display in job list widget even if job is expired but only for anonymous uses, behaves correctly when logged in as an admin.

## To reproduce
1. Log out
2. Go to https://www.cityofmontclair.org/employment-opportunities/ see jobs posting at bottom of page
<img width="1250" alt="Screen Shot 2023-03-02 at 6 36 37 PM" src="https://user-images.githubusercontent.com/6032426/222589745-868ae72d-7555-4b52-9aad-0a852d3d0a3f.png">

## Expected behavior
Those listings should not be published and aren't if you're logged in as an admin:
![Screen Shot 2023-03-02 at 6 36 43 PM](https://user-images.githubusercontent.com/6032426/222589797-b10124fc-4faa-4cf3-a750-38c0e96d8ddc.png)

## Screenshots
See the job listings that were displaying are in fact expired:
![Screen Shot 2023-03-02 at 6 37 08 PM](https://user-images.githubusercontent.com/6032426/222589845-dcf77040-df52-4ac3-a5d3-7a55c9ae7168.png)

## Additional context
Usually content that expires is moved to draft, maybe that's what need to happen here or the jobs list widget itself needs to be adjusted.

## QA

Notes:

* 

Links:

*

**Comment by curtismchale** [comment] 2023-05-24 21:58
@kevindherman I can't reproduce this currently.

If I had to guess I think that a user who wasn't signed in got a cached version of the page. So the issue could have been that the cache wasn't refreshed by our post expiration plugin that moves stuff to draft. 

I'm closing this until we have a visible issue I can reproduce.

**Closed by curtismchale** 2023-05-24 21:58 UTC
Labels: bug, release, priority-2
