### ISSUE TITLE
WP e-signature enhancements

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#752] opened 2016-12-16 19:48 UTC
- [ ] RM from topnav
- [ ] Style sign popup in backend
- [ ] If I draw my signature, it doesn't save
- [ ] Look into pdf downloads?
- [ ] Backend: edit form page: https://www.cityofsanrafael.org/wp-admin/edit.php?post_type=esign&page=esign-edit-document&document_id=1

**Comment by kevindherman** [comment] 2016-12-19 16:12
@jlyon other items we discussed looking into:

- [ ] select all fields when building document from existing form
- [ ] ability for multiple admins to view e-signature documents
- [ ] hide page where e-signature document lives from search (or everything) since it's outside of the theme and likely a duplicate of the form in our document library

**Comment by kevindherman** [comment] 2017-01-17 18:43
@jlyon I'm assuming it'll be tough to get this into this release, can it be a priority for the next one?

**Comment by jlyon** [comment] 2017-08-11 21:15
@kevindherman moving this back to the backlog, ok?

**Comment by kevindherman** [comment] 2017-08-12 14:11
@jlyon sounds good.

It may come back in a month or so.

**Closed** 2019-02-08 09:59 UTC
Labels: pending close
