### ISSUE TITLE
Save page before leaving message still showing for some users

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#2036] opened 2022-05-11 18:11 UTC
**Source**

Williams County

**Describe the bug**

I saw the save before leaving page message when trouble-shooting WC.

**To Reproduce**
1. Go to the admin.
2. Open a page.
3. Leave the page.
4. See message.

**Expected behavior**

This shouldn't appear unless a page has actually been edited and the save button hasn't been selected.

**Screenshots**

<img width="883" alt="167917584-2bf0047a-9811-4d33-84a1-cc7f0329a03c" src="https://user-images.githubusercontent.com/1569463/167918084-ba96fcaf-dd66-4453-9b56-f9cc193701e2.png">

**Additional context**

From WC: 

> I do see that message, but that has been happening for quite a few months and only happens when I use Chrome. I think I might have reported it previously? It is tough to replicate because sometimes it happens and sometimes it doesn’t and with frequent browser updates it is hard to nail down a reason.

**Comment by lukefretwell** [comment] 2022-05-11 18:12
Note: I discovered this on Mac/Firefox.

**Comment by curtismchale** [comment] 2022-05-12 15:22
See the following commit for the "fix" that was previously applied: https://github.com/proudcity/wp-proud-theme/commit/41429a68bfefbe086994826ae5b67e2d41d03bef

Find the code here: https://github.com/proudcity/wp-proud-theme/blob/master/lib/setup.php

**Comment by lukefretwell** [comment] 2022-06-06 19:01
@curtismchale I'm getting this on https://populations.proudcity.com. As soon as I save and try to leave the page, get this message:

> This page is asking you to confirm that you want to leave — information you’ve entered may not be saved.

**Comment by lukefretwell** [comment] 2022-06-06 19:01
We should make sure the fix has been added to city template as this is a website we set up in the last few weeks.

**Comment by kevindherman** [comment] 2022-06-07 16:37
Seems to be a FF issue.

**Comment by kevindherman** [comment] 2022-06-07 16:38
@lukefretwell to test not using pagebuilding (text or visual editor).

**Comment by curtismchale** [comment] 2022-08-25 13:10
Closed as duplicate of: https://github.com/proudcity/wp-proudcity/issues/2096

**Closed by curtismchale** 2022-08-25 13:10 UTC
Labels: bug
